### ISSUE TITLE
HTTPS Everywhere but the homepage

### ISSUE THREAD

**Issue by omnicons** [Poniverse/Ponyville-Live#5]
For now not enough stations currently have secured streams to allow for the homepage to be served over TLS, but the rest of the site should be able to be served over TLS rather than actively downgrading the connection.

**Comment by AmonBune** [comment]
I also cannot understand this. Why do you redirect the requests from HTTPS to HTTP? HTTP is not secure while HTTPS is. And there exist certificate authorities that give out free certs (see Let's Encrypt)
Of course you rely on third party sites but that doesn't make a huge difference. Yes, you will get a mixed content warning in the browser when a third party isn't HTTPS but at least the mane site would be secure then.

**Comment by omnicons** [comment]
@AmonBune Because the radio players no longer function when using HTTPS due to the streams themselves not being served over HTTPS. We have been trying for about a year to get the streams that we host to switch over to HTTPS to no avail, so we're still unable to make the jump.

**Comment by omnicons** [comment]
A note: The streams that we host are 3rd party streams and we have no direct control over them, so making the switch for them is also not possible.

**Comment by AppleDash** [comment]
@AmonBune Also important to note that the site already has a cert, given that the HTTPS -> HTTP redirect worked without an insecure connection warning. So that's evidently not the problem... What @omnicons mentioned, however, is. You're welcome to join us and fix it for us if you want - it's just that it seems nobody has had the time :P

**Comment by AmonBune** [comment]
@AppleDash @omnicons I will certainly look into this and will try to make the radio stations work with HTTPS since it sounds a bit fishy to me that it doesn't. There has to be a solution.

(But first I have to download the thing on a bare metal linux. I tried to install virtualbox inside an LXD container but this doesn't seem to work, sad.)
